company.name=SeatSure
company.version=1.0.0
company.environment=Development

eureka.client.service-url.defaultZone=http://localhost:8761/eureka

eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true