server.port=8082

eureka.client.service-url.defaultZone=http://localhost:8761/eureka

eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/seatsure_auth
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true

spring.flyway.locations=classpath:db/migration

jwt.secret=4B7A93A1C2D4E6F8A9B1C3D5E7F9A2B4C6D8E1F3A5B7C9D2E4F6A8B1C3D5E7F9
jwt.expiration=86400000